services:
  app:
    build:
      context: .
    ports:
      - "5000"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.config:/etc/nginx.conf:ro
    depends_on:
      - app
    ports:
      - "80:80"
